In [41]:
import requests
import json
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
url = "https://maps.googleapis.com/maps/api/elevation/json"
p1=np.array([24.663513, 121.182540])
p2=np.array([24.534208, 121.655832])
p3=np.array([23.188591, 120.532673])
p4=np.array([23.012812, 121.095572])

for t1 in np.linspace(0,1,5):
    for t2 in np.linspace(0,1,20):
        data=[]
        locations=''
        p=(p1*t1+p2*(1.0-t1))*t2+(p3*t1+p4*(1.0-t1))*(1.0-t2)
        lat=p[0]
        lon=p[1]
        size=100
        n=0
        n_sum=0;
        for i in range(-size//2,size-size//2):
            for j in range(-size//2,size-size//2):
                locations+="{:.3f}".format(lat-i*0.001)+","+"{:.3f}".format(lon+j*0.001)
                n+=1;n_sum+=1;
                if n == 510:
                    param = {"locations":locations,"key": "AIzaSyD57zm-VEPud6YTbl6XKpu7kZIdlHxHZIQ" }     
                    r = requests.get(url, param)
                    for k in range(n):
                        data.append(r.json()['results'][k]['elevation'] )
                    locations=''
                    n=0
                    print((str)(n_sum)+'/'+(str)(size**2))
                else: locations+='|'
        if n!=0:
            locations=locations[:-1]
            param = {"locations":locations,"key": "AIzaSyD57zm-VEPud6YTbl6XKpu7kZIdlHxHZIQ" } 
            r = requests.get(url, param)
            for i in range(n):
                data.append(r.json()['results'][i]['elevation'] )

        
        total = float(255 ** 3)
        max_ = float(max(data))
        min_ = float(min(data))
        data = [float(((num - min_) / ((max_ - min_)/total))) for num in data]
        
        data=np.array(data,dtype='int64')
        print(data)
        output = np.zeros([size*size, 3])
        for j in range(len(data)):
            value = [0, 0, 0]
            num = data[j]
            i = 0
            while num > 255:
                value[i] = num % 256
                num /= 256
                i += 1

            value[i] = num
            for k in range(3):
                output[j][k] = value[k]
        print(output)                    
        output.resize(size,size,3)
        cv2.imwrite('Heightmap/Taiwan/'+"{:.3f}".format(lat) +','+"{:.3f}".format(lon)+'.png', output)
        

510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[12917927 12526609 12403672 ...   103929    86232    60710]
[[167.          28.65234375 197.11192322]
 [ 17.          36.06640625 191.1408844 ]
 [216.          67.84375    189.26501465]
 ...
 [249.         149.97265625   1.58583069]
 [216.          80.84375      1.3157959 ]
 [ 38.         237.1484375    0.        ]]
510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[5483703 5023073 4535956 ...    3532    2396       0]
[[183.         172.71484375  83.67466736]
 [ 97.         165.37890625  76.64601135]
 [148.          54.578125    69.2131958 ]
 ...
 [204.          13.796875     0.        ]
 [ 92.           9.359375     0.       

510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[15655574 15353674 14827767 ...  4458046  4361567  4153198]
[[150.         226.5859375  238.88510132]
 [ 74.          71.2890625  234.2784729 ]
 [247.          64.96484375 226.25376892]
 ...
 [ 62.           6.2421875   68.02438354]
 [ 95.         141.37109375  66.55223083]
 [110.          95.4296875   63.37277222]]
510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[7489097 7393751 7062555 ... 5949730 6331368 6745366]
[[ 73.          70.28515625 114.27455139]
 [215.         209.83984375 112.81968689]
 [ 27.         196.10546875 107.76603699]
 ...
 [ 34.         201.1328125   90.78567505]
 [232.         155.90625     96.6090087

510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[13608979 14198876 14740700 ...  7294759  7207903  7255257]
[[ 19.         168.07421875 207.65653992]
 [ 92.         168.359375   216.65765381]
 [220.         236.859375   224.92523193]
 ...
 [ 39.          79.15234375 111.30918884]
 [223.         251.87109375 109.98387146]
 [217.         180.84765625 110.70643616]]
510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[10487814 10317575 10149692 ...  2618329  2849980  3011682]
[[  6.           8.0234375  160.03134155]
 [  7.         111.02734375 157.43370056]
 [ 60.         223.234375   154.87200928]
 ...
 [217.         243.84765625  39.95252991]
 [188.         124.734375    43.4

510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[  526554   322893   281462 ... 13076257 12870124 12780326]
[[218.           8.8515625    8.03457642]
 [ 77.         237.30078125   4.92695618]
 [118.          75.4609375    4.29476929]
 ...
 [ 33.         135.12890625 199.52784729]
 [236.          97.921875   196.38250732]
 [ 38.           3.1484375  195.01229858]]
510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[4224700 4658575 5115904 ... 8665342 8456359 8152943]
[[188.         118.734375    64.46380615]
 [143.          21.55859375  71.08421326]
 [  0.          16.          78.0625    ]
 ...
 [254.          56.9921875  132.22262573]
 [167.           8.65234375 129.0337982

510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[4926559 5203178 5545099 ... 5332654 5688387 6192927]
[[ 95.          44.37109375  75.17332458]
 [234.         100.9140625   79.39419556]
 [139.         156.54296875  84.61149597]
 ...
 [174.          94.6796875   81.36984253]
 [ 67.         204.26171875  86.79789734]
 [ 31.         127.12109375  94.49656677]]
510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[ 8170975  8223484  8390172 ... 16189244 16175432 16321917]
[[223.         173.87109375 124.67918396]
 [252.         122.984375   125.48040771]
 [ 28.           6.109375   128.02386475]
 ...
 [ 60.           7.234375   247.02825928]
 [ 72.         209.28125    246.8175048

510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[6921113 8238884 8941851 ... 1869565 2095072 2427663]
[[153.         155.59765625 105.60780334]
 [ 36.         183.140625   125.71539307]
 [ 27.         113.10546875 136.44181824]
 ...
 [253.         134.98828125  28.52729797]
 [224.         247.875       31.96826172]
 [ 15.          11.05859375  37.04319763]]
510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[ 9807103 10274453 10660674 ...  3156494  3073603  3118838]
[[255.         164.99609375 149.64451599]
 [149.         198.58203125 156.77571106]
 [ 66.         171.2578125  162.66897583]
 ...
 [ 14.          42.0546875   48.16427612]
 [ 67.         230.26171875  46.8994598

510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[ 5175106  5372355  5025327 ... 15537973 15954577 16531767]
[[ 66.         247.2578125   78.96585083]
 [195.         249.76171875  81.97563171]
 [ 47.         174.18359375  76.68040466]
 ...
 [ 53.          23.20703125 237.09065247]
 [145.         114.56640625 243.44752502]
 [ 55.          65.21484375 252.25474548]]
510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[ 7710557  7207743  6807910 ... 15071571 14648580 14590831]
[[ 93.         167.36328125 117.65376282]
 [ 63.         251.24609375 109.98143005]
 [102.         225.3984375  103.88046265]
 ...
 [ 83.         249.32421875 229.97392273]
 [  4.         133.015625   223.5

In [ ]:
import faster_than_requests as requests
import json
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
url = "https://maps.googleapis.com/maps/api/elevation/json"
p1=np.array([27.162822, 117.929151])
p2=np.array([27.494665, 113.754346])
p3=np.array([24.952233, 117.819288])
p4=np.array([24.772807, 113.820264])

for t1 in np.linspace(0,1,34):
    for t2 in np.linspace(0,1,30):
        data=[]
        locations=''
        p=(p1*t1+p2*(1.0-t1))*t2+(p3*t1+p4*(1.0-t1))*(1.0-t2)
        lat=p[0]
        lon=p[1]
        size=100
        n=0
        n_sum=0;
        for i in range(-size//2,size-size//2):
            for j in range(-size//2,size-size//2):
                locations+="{:.3f}".format(lat-i*0.001)+","+"{:.3f}".format(lon+j*0.001)
                n+=1;n_sum+=1;
                if n == 300:
                    param = {"locations":locations,"key": "AIzaSyD57zm-VEPud6YTbl6XKpu7kZIdlHxHZIQ" }     
                    r = requests.get(url, param)
                    for k in range(n):
                        data.append(r.json()['results'][k]['elevation'] )
                    locations=''
                    n=0
                    #print((str)(n_sum)+'/'+(str)(size**2))
                else: locations+='|'
        if n!=0:
            locations=locations[:-1]
            param = {"locations":locations,"key": "AIzaSyD57zm-VEPud6YTbl6XKpu7kZIdlHxHZIQ" } 
            r = requests.get(url, param)
            for i in range(n):
                data.append(r.json()['results'][i]['elevation'] )
        min_=min(data)
        max_=max(data)
        data=[(data[i]-min_)/(float(max_-min_)/255.0) for i in range(len(data))]
        data=np.array(data,dtype='uint8')
        data=data.reshape(size,size)
        Image.fromarray(data).save('Heightmap\\中國東南\\'+"{:.3f}".format(lat) +','+"{:.3f}".format(lon)+'.bmp','bmp')