In [47]:
# Taiwan

import requests
import json
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
url = "https://maps.googleapis.com/maps/api/elevation/json"
p1=np.array([24.663513, 121.182540])
p2=np.array([24.534208, 121.655832])
p3=np.array([23.188591, 120.532673])
p4=np.array([23.012812, 121.095572])

for t1 in np.linspace(0,1,5):
    for t2 in np.linspace(0,1,20):
        data=[]
        locations=''
        p=(p1*t1+p2*(1.0-t1))*t2+(p3*t1+p4*(1.0-t1))*(1.0-t2)
        lat=p[0]
        lon=p[1]
        size=100
        n=0
        n_sum=0;
        for i in range(-size//2,size-size//2):
            for j in range(-size//2,size-size//2):
                locations+="{:.3f}".format(lat-i*0.001)+","+"{:.3f}".format(lon+j*0.001)
                n+=1;n_sum+=1;
                if n == 510:
                    param = {"locations":locations,"key": "AIzaSyD57zm-VEPud6YTbl6XKpu7kZIdlHxHZIQ" }     
                    r = requests.get(url, param)
                    for k in range(n):
                        data.append(r.json()['results'][k]['elevation'] )
                    locations=''
                    n=0
                    print((str)(n_sum)+'/'+(str)(size**2))
                else: locations+='|'
        if n!=0:
            locations=locations[:-1]
            param = {"locations":locations,"key": "AIzaSyD57zm-VEPud6YTbl6XKpu7kZIdlHxHZIQ" } 
            r = requests.get(url, param)
            for i in range(n):
                data.append(r.json()['results'][i]['elevation'] )

        
        total = float(255 ** 3)
        max_ = float(max(data))
        min_ = float(min(data))
        data = [float(((num - min_) / ((max_ - min_)/total))) for num in data]
        
        data=np.array(data,dtype='int64')
        print(data)
        output = np.zeros([size*size, 3])
        for j in range(len(data)):
            value = [0, 0, 0]
            num = data[j]
            i = 0
            while num > 255:
                value[i] = num % 256
                num /= 256
                i += 1

            value[i] = num
            for k in range(3):
                output[j][k] = value[k]
        print(output)                    
        output.resize(size,size,3)
        cv2.imwrite('Heightmap/Taiwan/'+"{:.3f}".format(lat) +','+"{:.3f}".format(lon)+'.png', output)
        

510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[12917927 12526609 12403672 ...   103929    86232    60710]
[[167.          28.65234375 197.11192322]
 [ 17.          36.06640625 191.1408844 ]
 [216.          67.84375    189.26501465]
 ...
 [249.         149.97265625   1.58583069]
 [216.          80.84375      1.3157959 ]
 [ 38.         237.1484375    0.        ]]
510/10000
1020/10000
1530/10000
2040/10000
2550/10000
3060/10000
3570/10000
4080/10000
4590/10000
5100/10000
5610/10000
6120/10000
6630/10000
7140/10000
7650/10000
8160/10000
8670/10000
9180/10000
9690/10000
[5483703 5023073 4535956 ...    3532    2396       0]
[[183.         172.71484375  83.67466736]
 [ 97.         165.37890625  76.64601135]
 [148.          54.578125    69.2131958 ]
 ...
 [204.          13.796875     0.        ]
 [ 92.           9.359375     0.       

KeyboardInterrupt: 

In [ ]:
# China southeast

import requests
import json
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
url = "https://maps.googleapis.com/maps/api/elevation/json"
p1=np.array([27.162822, 117.929151])
p2=np.array([27.494665, 113.754346])
p3=np.array([24.952233, 117.819288])
p4=np.array([24.772807, 113.820264])

for t1 in np.linspace(0,1,34):
    for t2 in np.linspace(0,1,30):
        data=[]
        locations=''
        p=(p1*t1+p2*(1.0-t1))*t2+(p3*t1+p4*(1.0-t1))*(1.0-t2)
        lat=p[0]
        lon=p[1]
        size=100
        n=0
        n_sum=0;
        for i in range(-size//2,size-size//2):
            for j in range(-size//2,size-size//2):
                locations+="{:.3f}".format(lat-i*0.001)+","+"{:.3f}".format(lon+j*0.001)
                n+=1;n_sum+=1;
                if n == 300:
                    param = {"locations":locations,"key": "AIzaSyD57zm-VEPud6YTbl6XKpu7kZIdlHxHZIQ" }     
                    r = requests.get(url, param)
                    for k in range(n):
                        data.append(r.json()['results'][k]['elevation'] )
                    locations=''
                    n=0
                    print((str)(n_sum)+'/'+(str)(size**2))
                else: locations+='|'
        if n!=0:
            locations=locations[:-1]
            param = {"locations":locations,"key": "AIzaSyD57zm-VEPud6YTbl6XKpu7kZIdlHxHZIQ" } 
            r = requests.get(url, param)
            for i in range(n):
                data.append(r.json()['results'][i]['elevation'] )
        min_=min(data)
        max_=max(data)
        data=[(data[i]-min_)/(float(max_-min_)/255.0) for i in range(len(data))]
        data=np.array(data,dtype='uint8')
        data=data.reshape(size,size)
        Image.fromarray(data).save('Heightmap\\中國東南\\'+"{:.3f}".format(lat) +','+"{:.3f}".format(lon)+'.bmp','bmp')